---
title: 'Lab 02: Data Wrangling'
output:
  html_document:
    toc: yes
    toc_float: yes
    hide_code: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#libraries
library(tidyverse)
```

**Markdown Author:** Jessie Bell, 2023

**Libraries Used:** tidyverse

**Answers:** <span style="color:#90b9c3"> **Pewter Blue** </span>

**View Jessie's data wrangling steps**
[**here**](https://github.com/JBell39/ESCI502/blob/main/Docs/Bell_datawrangle_fishies_Lab02.txt) 😎



```{r, read in data}
fishiesData <- read.csv("fishies_cleaned.csv")

```


# Questions {.tabset}

## <span style="color:#90b9c3"> **Q1** </span>

##### **Answers:** <span style="color:#90b9c3"> **Insert Answer here** </span>

## <span style="color:#90b9c3"> **Practice** </span>

#### Using Penguin Data

```{r, practice}
penguinData <- palmerpenguins::penguins

#quick table
penguinData |>
  drop_na(bill_length_mm) |>
  summarise(bill_length_MEAN = mean(bill_length_mm), 
            bill_length_MIN = min(bill_length_mm), 
            bill_length_MAX = max(bill_length_mm))

#summarize single column 
penguinData |>
  drop_na(body_mass_g) |>
  summarise(body_mass_MEAN = mean(body_mass_g))

#What if we want to dimensionally analyze that column as kg instead of g? Conversion factor: 1000 g = 1 kg, mm 
penguinData |>
  drop_na(body_mass_g) |>
  summarise(body_mass_kg_MEAN = mean(body_mass_g/1000), 
            body_mass_kg_SD =sd(body_mass_g/1000),
            flipper_length_kg_MEAN = mean(flipper_length_mm/10), #flipper length is in mm and needs converted to cm. 10 mm = 1 cm 
            flipper_length_kg_SD = sd(flipper_length_mm/10))

#Now you can separate your data by categories. Say you would like to use species to group your data

penguinData |>
  drop_na(body_mass_g) |>
  group_by(species) |> #now you are grouping by species
  summarise(body_mass_g_MEAN = mean(body_mass_g)) #NICE. Similar to Tapply() function

#Now to create a frequency table: 

penguinData |>
  group_by(species) |>
  summarise(n=n()) #remember function n()

#Note: if all you want is a frequency table, then use the function count() or tally() since this is a bit easier than the n() function. 

penguinData |>
  group_by(species) |>
  tally()

```



## <span style="color:#90b9c3"> **References** </span>
1. [Data Wrangling](https://datacarpentry.org/spreadsheet-ecology-lesson/05-exporting-data.html)
2. [Tidyverse Piping](https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/#:~:text=Both%20operators%20(%20%7C%3E%20and%20%25,of%20R%20for%20Data%20Science.), what's the diff?
3. HW: Tidy Data in Spreadsheets and R by Kathryn Sobocinski
